import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'instructor.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'instructor.g.dart';

@freezed
@JsonSerializable()
class Instructor with _$Instructor {
    final String name;
    final String webpage;

    Instructor({
      required this.name,
      required this.webpage,
    });

    factory Instructor.fromJson(Map<String, Object?> json) => _$InstructorFromJson(json);

    Map<String, Object?> toJson() => _$InstructorToJson(this);
}